<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260929093741 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create school and school_alias tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE school (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, official_name VARCHAR(255) NOT NULL, city VARCHAR(100) NOT NULL, type VARCHAR(20) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE school_alias (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, normalized_name VARCHAR(255) NOT NULL, kind VARCHAR(20) NOT NULL, school_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_school_alias_normalized_name ON school_alias (normalized_name)');
        $this->addSql('CREATE UNIQUE INDEX uniq_school_alias_school_normalized_name ON school_alias (school_id, normalized_name)');
        $this->addSql('CREATE INDEX IDX_3F96DD8EC32A47EE ON school_alias (school_id)');
        $this->addSql('ALTER TABLE school_alias ADD CONSTRAINT FK_3F96DD8EC32A47EE FOREIGN KEY (school_id) REFERENCES school (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE school_alias DROP CONSTRAINT FK_3F96DD8EC32A47EE');
        $this->addSql('DROP TABLE school');
        $this->addSql('DROP TABLE school_alias');
    }
}
